# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fastener_StrengthCriteria_110918.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 388)
        MainWindow.setStyleSheet("QWidget #tab{\n"
"    background-color: rgb(234, 234, 234);\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel{\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"    text-decoration: underline;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabFastenerWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabFastenerWidget.setGeometry(QtCore.QRect(0, 0, 641, 581))
        self.tabFastenerWidget.setMaximumSize(QtCore.QSize(641, 16777215))
        self.tabFastenerWidget.setBaseSize(QtCore.QSize(3, 0))
        self.tabFastenerWidget.setStyleSheet("#tab, #tab_2 , #tab_3 {\n"
"background-color: rgb(212, 212, 212);\n"
"}")
        self.tabFastenerWidget.setObjectName("tabFastenerWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.calculateButton = QtWidgets.QPushButton(self.tab)
        self.calculateButton.setGeometry(QtCore.QRect(20, 210, 101, 23))
        self.calculateButton.setObjectName("calculateButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 20, 201, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tension_shear.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 240, 208, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.safetyMargin = QtWidgets.QLineEdit(self.layoutWidget)
        self.safetyMargin.setObjectName("safetyMargin")
        self.horizontalLayout.addWidget(self.safetyMargin)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 215, 154))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.yieldStress = QtWidgets.QLineEdit(self.layoutWidget1)
        self.yieldStress.setObjectName("yieldStress")
        self.verticalLayout.addWidget(self.yieldStress)
        self.nominalDiameter = QtWidgets.QLineEdit(self.layoutWidget1)
        self.nominalDiameter.setObjectName("nominalDiameter")
        self.verticalLayout.addWidget(self.nominalDiameter)
        self.shearOne = QtWidgets.QLineEdit(self.layoutWidget1)
        self.shearOne.setObjectName("shearOne")
        self.verticalLayout.addWidget(self.shearOne)
        self.shearTwo = QtWidgets.QLineEdit(self.layoutWidget1)
        self.shearTwo.setObjectName("shearTwo")
        self.verticalLayout.addWidget(self.shearTwo)
        self.axial = QtWidgets.QLineEdit(self.layoutWidget1)
        self.axial.setStyleSheet("")
        self.axial.setObjectName("axial")
        self.verticalLayout.addWidget(self.axial)
        self.safetyFactor = QtWidgets.QLineEdit(self.layoutWidget1)
        self.safetyFactor.setObjectName("safetyFactor")
        self.verticalLayout.addWidget(self.safetyFactor)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tabFastenerWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.calculateShearMargin = QtWidgets.QPushButton(self.tab_2)
        self.calculateShearMargin.setGeometry(QtCore.QRect(20, 220, 101, 23))
        self.calculateShearMargin.setObjectName("calculateShearMargin")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 214, 178))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.shearStrength = QtWidgets.QLineEdit(self.layoutWidget2)
        self.shearStrength.setObjectName("shearStrength")
        self.gridLayout_2.addWidget(self.shearStrength, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.nominalDiameter_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.nominalDiameter_2.setObjectName("nominalDiameter_2")
        self.gridLayout_2.addWidget(self.nominalDiameter_2, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.e = QtWidgets.QLineEdit(self.layoutWidget2)
        self.e.setObjectName("e")
        self.gridLayout_2.addWidget(self.e, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.thickness = QtWidgets.QLineEdit(self.layoutWidget2)
        self.thickness.setObjectName("thickness")
        self.gridLayout_2.addWidget(self.thickness, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.shearOneComponent = QtWidgets.QLineEdit(self.layoutWidget2)
        self.shearOneComponent.setObjectName("shearOneComponent")
        self.gridLayout_2.addWidget(self.shearOneComponent, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 5, 0, 1, 1)
        self.shearTwoComponent = QtWidgets.QLineEdit(self.layoutWidget2)
        self.shearTwoComponent.setObjectName("shearTwoComponent")
        self.gridLayout_2.addWidget(self.shearTwoComponent, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 6, 0, 1, 1)
        self.safetyFactor2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.safetyFactor2.setObjectName("safetyFactor2")
        self.gridLayout_2.addWidget(self.safetyFactor2, 6, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 260, 208, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.shearSafetyMargin = QtWidgets.QLineEdit(self.layoutWidget3)
        self.shearSafetyMargin.setObjectName("shearSafetyMargin")
        self.gridLayout_3.addWidget(self.shearSafetyMargin, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(260, 30, 221, 151))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/images/ShearTearOut.PNG"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.tabFastenerWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.calculateBoltBearing = QtWidgets.QPushButton(self.tab_3)
        self.calculateBoltBearing.setGeometry(QtCore.QRect(20, 240, 101, 23))
        self.calculateBoltBearing.setObjectName("calculateBoltBearing")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 280, 208, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.bearingSafetyMargin = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.bearingSafetyMargin.setObjectName("bearingSafetyMargin")
        self.gridLayout_5.addWidget(self.bearingSafetyMargin, 0, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 20, 188, 204))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.bearingUpper = QtWidgets.QLineEdit(self.layoutWidget4)
        self.bearingUpper.setObjectName("bearingUpper")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bearingUpper)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.bearingLower = QtWidgets.QLineEdit(self.layoutWidget4)
        self.bearingLower.setObjectName("bearingLower")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bearingLower)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.nominalDiameter3 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.nominalDiameter3.setObjectName("nominalDiameter3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nominalDiameter3)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.e_2 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.e_2.setObjectName("e_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.e_2)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.thickness2 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.thickness2.setObjectName("thickness2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.thickness2)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.shearTwo2 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.shearTwo2.setObjectName("shearTwo2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.shearTwo2)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.safetyFactor3 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.safetyFactor3.setObjectName("safetyFactor3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.safetyFactor3)
        self.shearOne2 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.shearOne2.setObjectName("shearOne2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.shearOne2)
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(260, 30, 221, 161))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/images/BoltBearing.PNG"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.tabFastenerWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 21))
        self.menubar.setObjectName("menubar")
        self.menuFastenerCalcs = QtWidgets.QMenu(self.menubar)
        self.menuFastenerCalcs.setObjectName("menuFastenerCalcs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFastenerCalcs.menuAction())

        self.retranslateUi(MainWindow)
        self.tabFastenerWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate Margin"))
        self.label_6.setText(_translate("MainWindow", "Safety Margin"))
        self.label_2.setText(_translate("MainWindow", "Yield Stress"))
        self.label_3.setText(_translate("MainWindow", "No. Diameter"))
        self.label_4.setText(_translate("MainWindow", "Shear Stress x"))
        self.label_5.setText(_translate("MainWindow", "Shear Stress y"))
        self.label_7.setText(_translate("MainWindow", "Axial"))
        self.label_8.setText(_translate("MainWindow", "Safety Factor"))
        self.tabFastenerWidget.setTabText(self.tabFastenerWidget.indexOf(self.tab), _translate("MainWindow", "Fastener Analysis"))
        self.calculateShearMargin.setText(_translate("MainWindow", "Calculate Margin"))
        self.label_9.setText(_translate("MainWindow", "Shear Strength"))
        self.label_10.setText(_translate("MainWindow", "No. Diameter"))
        self.label_11.setText(_translate("MainWindow", "e"))
        self.label_12.setText(_translate("MainWindow", "thickness"))
        self.label_13.setText(_translate("MainWindow", "ShearOne"))
        self.label_14.setText(_translate("MainWindow", "ShearTwo"))
        self.label_15.setText(_translate("MainWindow", "Safety Factor"))
        self.label_16.setText(_translate("MainWindow", "Safety Margin"))
        self.tabFastenerWidget.setTabText(self.tabFastenerWidget.indexOf(self.tab_2), _translate("MainWindow", "Shear Tear Out"))
        self.calculateBoltBearing.setText(_translate("MainWindow", "Calculate Margin"))
        self.label_26.setText(_translate("MainWindow", "Safety Margin"))
        self.label_17.setText(_translate("MainWindow", "bearingUpper"))
        self.label_18.setText(_translate("MainWindow", "bearingLower"))
        self.label_19.setText(_translate("MainWindow", "No. Diameter"))
        self.label_20.setText(_translate("MainWindow", "e"))
        self.label_21.setText(_translate("MainWindow", "thickness"))
        self.label_22.setText(_translate("MainWindow", "shearOne"))
        self.label_23.setText(_translate("MainWindow", "shearTwo"))
        self.label_24.setText(_translate("MainWindow", "SafetyFactor"))
        self.tabFastenerWidget.setTabText(self.tabFastenerWidget.indexOf(self.tab_3), _translate("MainWindow", "Bolt Bearing"))
        self.menuFastenerCalcs.setTitle(_translate("MainWindow", "FastenerCalcs"))

import resource_rc
